### ISSUE TITLE
imwri crash using argument as path

### ISSUE THREAD

**Issue by cyaoeu** [vapoursynth/vapoursynth#487] opened 2019-08-24 02:57 UTC
Using an argument in a path causes a crash in imwri. Maybe because of decode?

.vpy:
```python
import vapoursynth as vs
core = vs.get_core()

str = str.decode("utf-8")
clip = core.std.BlankClip()
clip = clip[0]
# works
#clip = core.imwri.Write(clip, "png", "C:/vsedit/test%04d.png")

#crash
clip = core.imwri.Write(clip, "png", "C:/vsedit/" + str + "/test%04d.png")
clip.set_output()
```

.py:
```python
import subprocess

cmd = ["vspipe", "-a", "str=string", "C:/VSEdit/imwribug.vpy", "NUL"]
subprocess.call(cmd)
```

**Comment by HolyWu** [comment] 2019-08-24 06:16
`str` is a keyword representing a type object. Use another variable name.

**Comment by HolyWu** [comment] 2019-08-24 06:22
I can't reproduce. It writes the png file just fine.

**Comment by dubhater** [comment] 2019-08-24 12:56
What does the crash look like? What actually happens? Are there any error messages?

**Comment by cyaoeu** [comment] 2019-08-24 14:01
> I can't reproduce. It writes the png file just fine.

Interesting, for me it doesn't work...



> What does the crash look like? What actually happens? Are there any error messages?

No error message, just a "vspipe.exe has stopped working   A problem caused the..." standard dialog box.

**Comment by cyaoeu** [comment] 2019-08-24 14:08
Debug button shows this in VS2017:
Unhandled exception at 0x00007FF8EFEB45A7 (ntdll.dll) in vspipe.exe: 0xC0000005: Access violation reading location 0x00000020A6300000. occurred

**Comment by cyaoeu** [comment] 2019-08-24 17:45
For me it works if the folder exists and crashes if the folder doesn't, so when used with a script you need to make sure the folder exists because imwri will not create it and will not error out nicely but will instead crash.

So not a huge issue but I'm leaving this issue open because it's still a crash.

**Comment by kblomster** [comment] 2019-09-09 09:56
@cyaoeu Does it work if you change the variable name from `str` to something else? `str()` is a Python builtin function and while you can use its name for your own variables, it's kinda weird to do so. I don't remember off the top of my head how exactly vspipe sets script variables but it might cause weird issues.

**Comment by stuxcrystal** [comment] 2019-09-09 14:04
As far as I understand it, the problem is that IMWRI crashes if it tries to create a new file inside a non-existing directory.

**Comment by myrsloik** [comment] 2019-10-20 18:00
Try this build:
https://www.dropbox.com/s/zopcwxqj4hk8192/imwri-r48-win64.7z?dl=1
https://www.dropbox.com/s/dcuwvqd8qbv5hug/imwri-r48-win32.7z?dl=1

I think it was caused by an ImageMagick bug where they allowed internal exceptions to escape and it got fixed in recent versions.

**Comment by myrsloik** [comment] 2020-01-26 17:47
Probably fixed and no feedback

**Comment by cyaoeu** [comment] 2020-01-29 14:31
Sorry for not responding.
For me:
`clip = core.imwri.Write(clip, "png", 'C:\invalidpath\file%04d.png')` crash
`clip = core.imwri.Write(clip, "png", 'C:\validpath\file%04d.png')` crash
`clip = core.imwri.Write(clip, "png", r'C:\invalidpath\file%04d.png')` crash
`clip = core.imwri.Write(clip, "png", r'C:\validpath\file%04d.png')` works
But again it doesn't really matter if there's one way that works.

**Comment by myrsloik** [comment] 2024-04-29 18:41
BestSource exists now and can do everything except write (which you really shouldn't do this way anyway)

**Closed by myrsloik** 2024-04-29 18:41 UTC
