### ISSUE TITLE
Missing output frames when working with python subprocess

### ISSUE THREAD

**Issue by luglio** [vapoursynth/vapoursynth#608] opened 2020-07-28 05:31 UTC
When using python subprocess to pipe the output to an encoder, sometimes the last frames seem missing.
I'm with Ubuntu kernel 5.4.0, python 3.8.2, tried VS R50/master, encoder x264/x265.
The following test script may take a few minutes (and create several log files):
```python
#! /usr/bin/env python3
import subprocess
import vapoursynth as vs
#vs.core.num_threads = 1

def EncodeTest(idx):
    x264_cmd = ['x264', '-o', f'{idx:02}.264', '--log-level', 'debug', '--demuxer', 'y4m', '-']
    clip = vs.core.std.BlankClip(format=vs.YUV420P10, width=1280, height=720, color=[512]*3, length=100).text.FrameNum(5)
    with open(f'{idx:02}.log', 'w') as log:
        enc_proc = subprocess.Popen(x264_cmd, stdin=subprocess.PIPE, stderr=log)
        clip.output(enc_proc.stdin, y4m=True)
        enc_proc.communicate()
    with open(f'{idx:02}.log', 'r') as log:
        last_line = log.readlines()[-1][:-1]
        print(f'{idx:02} | ' + last_line)

for idx in range(100):
    EncodeTest(idx)
```
Expected output shown in the console should be like
```
00 | encoded 100 frames, 200.15 fps, 9.35 kb/s
01 | encoded 100 frames, 208.37 fps, 9.35 kb/s
02 | encoded 100 frames, 200.73 fps, 9.35 kb/s
......
```
up to 99, but I frequently found corrupted outputs like:
```
13 | encoded 91 frames, 189.33 fps, 18.99 kb/s
```
The missing frames were always the ending ones in my tests, verified by the frame numbers in the video.
When forcing `num_threads=1` the number seems less but they still exist.

**Comment by myrsloik** [comment] 2020-07-28 12:02
If it works in a normal shell it's most likely a python quirk. Did you test that?

**Comment by luglio** [comment] 2020-07-28 15:46
Missing frames happen both when I copy the test codes to an interpreter, and when I save as a file and run in shell.
Calling vspipe in subprocess seems always working though.

**Comment by stuxcrystal** [comment] 2020-07-29 18:01
https://weeb.moe/yqlzdt
I can reproduce this problem.

**Comment by myrsloik** [comment] 2020-07-29 19:57
I can reproduce it and it's definitely a python/subprocess/output function problem. Exactly which one I'm not sure. I did however find one definitive bug:
Errors from exceptions thrown inside frameDoneCallbackOutput are not properly thrown later on completion. The one in d.error is simply ignored. In case you're wondering the exception is because of a write to a closed pipe. Usually happens on the second plane of the last frame.
Speculations and pull requests for the error propagation and this thing in general welcome. Enough printf debugging for today...

**Comment by luglio** [comment] 2020-07-30 04:40
Just asking and may not be heuristic: why is vspipe + subprocess always working and what's the difference?
> Usually happens on the second plane of the last frame.

Sadly using GRAY8 video format doesn't get rid of the issue.

**Comment by myrsloik** [comment] 2020-07-30 08:54
Why it's always working: no idea.
What's the difference: not much, really. output() is an old transcription of vspipe to python more or less
What you can try: make a python script that calls output() directs it to stdout, pipe that into x264 from commanline/shell

**Comment by luglio** [comment] 2020-07-30 14:52
The following test scripts show some additional error message in the stderr.

script.py
```python
#! /usr/bin/env python3
import vapoursynth as vs
import sys
clip = vs.core.std.BlankClip(format=vs.YUV420P10, width=1280, height=720, color=[512]*3, length=100).text.FrameNum(5)
clip.output(sys.stdout, y4m=True)
```

test.py
```python
#! /usr/bin/env python3
import subprocess

def EncodeTest(idx):
    x264_cmd = ['x264', '-o', f'{idx:02}.264', '--log-level', 'debug', '--demuxer', 'y4m', '-']
    with open(f'{idx:02}.log', 'w') as log:
        with open(f'{idx:02}v.log', 'w') as vlog:
            vs_proc = subprocess.Popen(['/usr/bin/env', 'python3', 'script.py'], stdout=subprocess.PIPE, stderr=vlog)
            enc_proc = subprocess.Popen(x264_cmd, stdin=vs_proc.stdout, stderr=log)
            enc_proc.communicate()
    with open(f'{idx:02}.log', 'r') as log:
        last_line = log.readlines()[-1][:-1]
        print(f'{idx:02} | ' + last_line)

for idx in range(100):
    EncodeTest(idx)
```
For *some* of the failed instances, the stderr log for script.py is not empty:
```
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x1aac370)

Thread 0x00007f0543504700 (most recent call first):
<no Python frame>

Current thread 0x00007f054ff94740 (most recent call first):
<no Python frame>
```
Message found in /var/log/apport.log:
`ERROR: apport (pid 46951) Thu Jul 30 09:34:15 2020: called for pid 46925, signal 6, core limit 0, dump mode 1`

**Comment by stuxcrystal** [comment] 2020-07-31 08:41
Maybe it's time to update the implementation of `VideoNode.output`?

**Comment by myrsloik** [comment] 2020-07-31 09:40
I actually wanted to remove output() like 5 years ago already due to people thinking it was good and fast (it's not). With that piece of get_frame_async wrapping I now know it's the correct thing to do as well.

**Comment by stuxcrystal** [comment] 2020-07-31 12:01
I made a PR implementing my solution into the VapourSynth source.

It speeds up `VideoNode.frames` and using that to reimplement `VideoNode.output` making the latter easier to maintain while providing a speed boost to all other users of `VideoNode.frames`

**Comment by myrsloik** [comment] 2020-08-09 13:15
Fixed in doodle1 branch

**Closed by myrsloik** 2020-08-09 13:15 UTC
