### ISSUE TITLE
Resize error 3076: image shift or subwindow too great

### ISSUE THREAD

**Issue by stargazze** [vapoursynth/vapoursynth#374] opened 2018-03-17 22:33 UTC
When trying to use the [BalanceBorders function from muvsfunc](https://github.com/WolframRhodium/muvsfunc/blob/master/muvsfunc.py#L2613) or any similar function, I'm getting the following error:
```
Error on frame 0 request:
Resize error 3076: image shift or subwindow too great
```
Looks like [this issue](https://github.com/HomeOfVapourSynthEvolution/havsfunc/issues/1).
Thanks.

**Comment by WolframRhodium** [comment] 2018-03-18 14:13
Could you provide your script and information relate to your video?

**Comment by stargazze** [comment] 2018-03-18 17:17
Sure. Here is my script (I tried various values for BalanceBorders):
```
import vapoursynth as vs
import muvsfunc as muvs
core = vs.get_core()

source = core.ffms2.Source('video.mkv')
crop = core.std.CropRel(source, left=0, top=138, right=0, bottom=138)
filtered = muvs.BalanceBorders(crop, 0, 0, 4, 0)

filtered.set_output()
```
And the video properties of the mkv file:
```
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 1 h 31 min
Bit rate mode                            : Variable
Bit rate                                 : 27.9 Mb/s
Maximum bit rate                         : 39.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.561
Stream size                              : 17.8 GiB (94%)
Default                                  : Yes
Forced                                   : No
```

**Comment by WolframRhodium** [comment] 2018-03-18 23:57
I could not reproduce the problem using above information. I'm using VapourSynth R43, which version do you use?

**Comment by stargazze** [comment] 2018-03-19 10:42
I'm also using R43 (from [Arch repository](https://www.archlinux.org/packages/community/x86_64/vapoursynth/)). I tested with 3 different videos, I always have this error. I'm going to narrow down the issue by checking which line of BalanceBorders is responsible for it.

**Comment by stargazze** [comment] 2018-03-19 11:29
Well apparently it comes from CropRel. With a 1920x1080 video, the following script gives me the Resize error 3076:
```
import vapoursynth as vs
core = vs.get_core()

c = core.ffms2.Source('video.mkv')
last = core.std.CropRel(c, 0, 0, 4, 1074)

last.set_output()
```

**Comment by theChaosCoder** [comment] 2018-03-19 12:29
I tried your script on a 1080 BD source. No problems with BalanceBorders. Win10 x64 VS-R43. 
But I do get the same error _**Resize error 3076: image shift or subwindow too great**_  with
 `core.std.CropRel(c, 0, 0, 4, 1074)`

**Comment by HolyWu** [comment] 2018-03-19 12:56
CropRel has nothing to do with Resize error 3076. That error only appears when you preview in vsedit. Using vspipe or benchmark in vsedit works just fine. The problem stems from vsedit's invoking of resize filter when previewing. The following lines can easily reproduce the problem, even without preview in vsedit:
```python
clip = core.std.BlankClip(width=1920, height=8, format=vs.YUV420P8)
clip = core.resize.Bicubic(clip, format=vs.RGB24, matrix_in_s='709')
```

**Comment by stargazze** [comment] 2018-03-19 13:28
I also have the error when using vspipe:
```
import vapoursynth as vs
import muvsfunc as muvs
core = vs.get_core()

source = core.ffms2.Source('video.mkv')

last = muvs.BalanceBorders(source, 0, 0, 4, 0)

last.set_output()
```
With `vspipe --y4m script.vpy - | x264 --demuxer y4m - --output test.mkv`, I have:
```
Error: Failed to retrieve frame 0 with error: Resize error 3076: image shift or subwindow too great
Output 0 frames in 0.25 seconds (0.00 fps)
y4m [info]: 1920x1080p 0:0 @ 24000/1001 fps (cfr)
x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x264 [info]: profile High, level 4.0
```
Maybe I should try to recompile everything?

**Comment by stargazze** [comment] 2018-03-21 23:11
I have just reinstalled my OS, recompiled everything from source concerning vapoursynth and I still can't use balanceborders. If you can't reproduce the issue, I guess it comes either from my OS (Manjaro - Arch based) or from the version of ffms2 (last version: 2.23.1)? The following script works (source is 1920x1080 x264 mkv):
```
import vapoursynth as vs

core = vs.get_core()

source = core.ffms2.Source('video.mkv')

last = core.std.CropRel(source, 0, 0, 4, 1074)
last = core.resize.Point(last, 1920,  2)

last.set_output()
```
This one doesn't work (same source):
```
import vapoursynth as vs

core = vs.get_core()

source = core.ffms2.Source('video.mkv')

last = core.std.CropRel(source, 0, 0, 4, 1074)
last = core.resize.Point(last, 1920,  4)

last.set_output()
```

**Comment by HolyWu** [comment] 2018-05-06 11:55
I think it's fixed in https://github.com/sekrit-twc/zimg/commit/b0e451fdefa42d9b861769d4d547d3cdba89705c.

**Comment by myrsloik** [comment] 2018-05-06 15:45
Should be fixed in R44-test2 build. Report if not fixed...

**Closed by myrsloik** 2018-05-06 15:45 UTC

**Comment by stargazze** [comment] 2018-05-07 16:14
Looks like it's fixed. Thanks!
