### ISSUE TITLE
Add an option to remove matrix property in SplitPlanes function?

### ISSUE THREAD

**Issue by gundamftw** [vapoursynth/vapoursynth#844] opened 2022-01-25 02:47 UTC
When I'm doing `SplitPlanes` and convert the output clips to YUV, there's an error complaining about the GREY clips cannot be having a RGB matrix property. I would have to manually call `RemoveFrameProps` to remove it. Would it be better to just have this option within the `SplitPlanes` function?

**Comment by DJATOM** [comment] 2022-01-25 09:12
Make your own lancingfunc.py and put a wrapper that calls RemoveFrameProps and ShufflePlanes internally?

**Comment by myrsloik** [comment] 2022-01-25 09:16
The problem is that sometimes you want to keep it and sometimes not. And adding it back is far more annoying than removing it.

**Comment by gundamftw** [comment] 2022-01-25 11:14
As for casual users, I can see people getting stuck on this error not knowing what to do, because the matrix property was implicitly added and there's no documentation about it. Having the remove option within the `SplitPlanes` function helps for better look up in the documentation.

**Comment by RivenSkaye** [comment] 2022-02-05 14:08
Maybe a better solution would be to ignore the RGB matrix property on this type of conversion, but keeping it for when planes are merged back together again?

**Comment by myrsloik** [comment] 2023-08-20 15:35
Clear as MUD!
Here's another maybe improvement that's more general:
Add a prop_src argument to ShufflePlanes(), this would default to the first clip like now, any other clip or an empty array to clear all properties in the output.
Or maybe adding a similar argument to SplitPlanes() is better. Or both. Opinions?

**Comment by RivenSkaye** [comment] 2023-08-20 16:13
I think having it on both would be best.
Passing an extea arg isn't hard and still keeps it obvious it's a conscious decision made by the user, whilst allowing it on both functions.

Or perhaps the existing Enums could be extended to include an explicit ignore/remove value? On the Python side, `...` (`builtins.Ellipsis`) could be used to differentiate from `None` there. That Enum value could then be passed to the `resize` call to explicitly ignore any matrix on the source clip

**Closed** 2024-02-01 21:32 UTC
