### ISSUE TITLE
sub.Subtitle "corruption" on RGB48 clip

### ISSUE THREAD

**Issue by NSQY** [vapoursynth/vapoursynth#766] opened 2021-09-16 10:07 UTC
For some bizarre reason, this only happens when specifying color >= 129 (at this depth, not 8-bit scale). Text is generated correctly at values below this. I have not observed this behavior with other formats.

Very simply:
```
import vapoursynth as vs
core = vs.core

clip = core.std.BlankClip(format=vs.RGB48, color=[129]*3)
subtitle = core.sub.Subtitle(clip, text="Testing testing testing...").set_output()
```
color=[128]*3
![rgb48_128](https://user-images.githubusercontent.com/34185288/133593287-9e88ccbb-ae8b-45f1-976a-3c2f2efa9c3c.png)
color=[129]*3
![rgb48_129](https://user-images.githubusercontent.com/34185288/133593292-04ad0b05-472e-4f41-b816-576a3acdd718.png)

**Comment by sekrit-twc** [comment] 2021-09-17 00:07
Can't reproduce when manually blending the subtitles, with premultiplied both False and True. Corrupted text is also not affected by SetMaxCPU.

````
clip = core.std.BlankClip(format=vs.RGB48, color=[129]*3)
subtitle = core.sub.Subtitle(clip, text="Testing testing testing...", blend=False)
subtitle_alpha = core.std.PropToClip(subtitle)
subtitle = core.resize.Bicubic(subtitle, format=vs.RGB48)
subtitle_alpha = core.resize.Bicubic(subtitle_alpha, format=vs.RGB48)
clip = core.std.MaskedMerge(clip, subtitle, subtitle_alpha, premultiplied=False).set_output()
````

**Comment by sekrit-twc** [comment] 2021-09-18 11:39
Fixed in AKARIN branch

**Closed by sekrit-twc** 2021-09-18 11:39 UTC
