### ISSUE TITLE
[FR?] vspipe: output video and audio mixed when pipe to stdin (or 2 separate pipes)

### ISSUE THREAD

**Issue by sl1pkn07** [vapoursynth/vapoursynth#802] opened 2021-10-07 17:20 UTC
Hi

now, vspipe in linux can only output video or audio but not both in same time (or in separate pipe)

is possible add this feature?. in windows can do it throught VFW, but linux not have any method

i do that right now with 2 vspipe instaces, one with audio and other with video in two separate pipes, and "mixed" with mpv with external-file option, but seems draw much load time (i get massive framedrops in the player)

greetings

**Comment by myrsloik** [comment] 2021-10-09 09:43
Duplicate of #293

**Closed as completed by myrsloik** 2021-10-09 09:43 UTC
