### ISSUE TITLE
core.max_cache_size is ignored on linux

### ISSUE THREAD

**Issue by Infiziert90** [vapoursynth/vapoursynth#503] opened 2019-10-11 18:37 UTC
You can set core.max_cache_size, but Vapoursynth seemingly ignores it, so that the memory usage rises above the threshold without max_cache_size being enforced.

Under Windows, it also seems to be ignored, but only until about "max + 500MB", after which vapoursynth is cleaning up itself.

Arch Linux: 
vapoursynth-git
descale-git

test script:
https://pastebin.com/h0DkxxU4
You can use the test script directly in the Python shell.
Use the process command 2-3 times and your RAM usage should triple the max_cache_size. With each following execution, RAM usage continues to increase.

**Comment by sekrit-twc** [comment] 2020-05-02 15:15
Does memory usage increase indefinitely (i.e. leak)? core.max_cache_size does not control the amount of memory used by the process, but only the amount of memory explicitly retained for caches. The process memory usage is governed by OS-dependent factors, mainly whether the memory allocator ever releases memory to the system. Typically on Linux, freed memory is never returned to the OS.

**Comment by myrsloik** [comment] 2020-08-07 13:19
Is there any change with the doodle1 branch?

**Comment by 4re** [comment] 2020-08-07 19:50
That branch does not compile right now on Linux, something about md5. I don't have a build log right here, I can give you one with the error later if you need it.

**Comment by DJATOM** [comment] 2020-08-07 20:13
```
/usr/bin/ld: src/vspipe/vspipe.o: in function `outputFrame(VSFrameRef const*, VSPipeOutputData*)':
vspipe.cpp:(.text+0x15d8): undefined reference to `MD5_Update'
/usr/bin/ld: vspipe.cpp:(.text+0x177e): undefined reference to `MD5_Update'
/usr/bin/ld: src/vspipe/vspipe.o: in function `main':
vspipe.cpp:(.text.startup+0xb36): undefined reference to `MD5_Init'
/usr/bin/ld: vspipe.cpp:(.text.startup+0xba0): undefined reference to `MD5_Final'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `forkpty'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `openpty'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `pthread_create'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `pthread_key_create'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `sem_wait'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `sem_init'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `pthread_getspecific'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `sem_destroy'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `dlopen'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `pthread_key_delete'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `pthread_attr_setstacksize'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `pthread_kill'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `sem_post'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `sem_trywait'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `dlerror'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `dlsym'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `sem_timedwait'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `pthread_sigmask'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `pthread_getcpuclockid'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `pthread_setspecific'
/usr/bin/ld: ./.libs/libvapoursynth-script.so: undefined reference to `pthread_detach'
collect2: error: ld returned 1 exit status
make: *** [Makefile:1342: vspipe] Error 1
```

**Comment by myrsloik** [comment] 2020-08-07 20:49
Compilation now fixed on osx and linux

**Comment by myrsloik** [comment] 2020-08-09 13:16
Nobody?

**Comment by Infiziert90** [comment] 2020-08-09 13:21
I will test it later.

**Comment by 4re** [comment] 2020-08-13 00:44
When I run OP's script first it segfaults mid-run. On second run it spits this:
```
$ python vs-oom.py 
Core freed but 3022 filter instance(s) still exist
Core freed but 1865806080 bytes still allocated in framebuffers
```

**Comment by DJATOM** [comment] 2020-08-15 12:55
Last doodle1 commits results (Win10):
```
C:\Users\DJATOM\Desktop>py testrun.py
Core freed but 3020 filter instance(s) still exist
Core freed but 641650592 bytes still allocated in framebuffers

C:\Users\DJATOM\Desktop>py testrun.py
Core freed but 3020 filter instance(s) still exist
Core freed but 491478688 bytes still allocated in framebuffers

C:\Users\DJATOM\Desktop>py testrun.py
Core freed but 3020 filter instance(s) still exist
Core freed but 265347488 bytes still allocated in framebuffers

C:\Users\DJATOM\Desktop>py testrun.py
Core freed but 3020 filter instance(s) still exist
Core freed but 567791264 bytes still allocated in framebuffers

C:\Users\DJATOM\Desktop>py testrun.py
Core freed but 3020 filter instance(s) still exist
Core freed but 261385024 bytes still allocated in framebuffers
```

**Comment by myrsloik** [comment] 2020-08-15 13:45
This happens because Python doesn't free objects immediately when their reference count hits 0. For a hundred random small str it's no problem but for hundreds of frames it begins to add up very quickly. I've now added explicit calls for garbage collection to mitigate it which reduces the peak and leak ram usage by several GB.

The remaining reported leak I can't really explain. It could be a reference leak somewhere (either python or elsewhere). Ideas welcome.

**Comment by Kamekameha** [comment] 2020-08-18 05:40
> [...] Python doesn't free objects immediately when their reference count hits 0.

This doesn't sound right, though.  In CPython an object _does_ get de-allocated as soon as its reference count hits zero.  What the Cyclic Garbage Collector (the `gc` Python module) is in charge of is breaking reference cycles of unreachable objects so that the usual ref-counting could kick in.  There must certainly be something keeping those frames alive, and given that running a full garbage collection at certain points is having a positive effect I'm inclined to believe that there might be reference cycles somewhere around those frame objects.

**Comment by myrsloik** [comment] 2020-08-18 09:29
@Kamekameha Help me look. A few years back I did some extensive cycle breaking which did resolve most of the problems. That's why no VS objects directly references other objects (apart from Core) and instead use the underlying pointers.

**Comment by Kamekameha** [comment] 2020-08-19 08:13
Eh, I could try. For all we know, however, the cycles might be occurring on the user's end as well.  For starters, does this still happen when **not** using `asyncio` (as its use in the OP's sample script is effectively redundant)?

One alternative in the meantime could be for the `VideoFrame` to hold on a strong reference to the relevant `Core`, rather than just the pointer.  This should ensure that frame instances get de-allocated _before_ the core even if there are cycles elsewhere.

**Comment by Infiziert90** [comment] 2020-08-19 08:19
I tested it with the non async version before posting this issue, and I had the same problem.

The test script comes from a discord bot that needs asyncio, so that's the reason why.

**Comment by Kamekameha** [comment] 2020-08-19 08:25
I see.  What about just `VideoNode.get_frame()`?  Does that also keep nodes and frames alive?

**Comment by Kamekameha** [comment] 2020-08-19 08:30
Or, wait, by non async you mean that method?  Or not using `asyncio`?

**Comment by Infiziert90** [comment] 2020-08-19 08:35
Yes with non async I mean the get_frame() method. So that I could blame stux for not correctly implementing async method :p

Someone can test it with the new branch version, but that would not fix the endgoal because this error is only a real issue for long running reusable cores like discord Bots that use vs for something.

**Comment by DJATOM** [comment] 2020-08-19 11:13
Non-async version (https://pastebin.com/GRTrF451) doesn't complain about framebuffers for me.

**Comment by stuxcrystal** [comment] 2020-08-19 11:25
If you add `gc.collect()` like I did there, does the leak still occur?

https://github.com/vapoursynth/vapoursynth/pull/613/commits/b4c967a6f5d6fe00494b242990750e05f2b96cf2

**Comment by DJATOM** [comment] 2020-08-19 12:11
Yes, that one doesn't leak: https://pastebin.com/Y6B9DNu3

**Comment by myrsloik** [comment] 2020-08-20 14:21
I gave gc.get_referrers() a try and there's really nothing apart from the futures holding references to the frames. Should this be considered good enough now?

**Comment by luglio** [comment] 2020-09-21 23:10
Is there any approach to recycle graphics memory as well on Linux?

**Comment by quietvoid** [comment] 2021-03-06 15:43
I'm having trouble with regular async vspipe as well, the memory usage increases as more frames are processed, and eventually it gets killed because OOM.

I've noticed lowering VS threads helps mitigate the issue, but with more complex scripts the memory still increases too much.

I have tested both non-async and async versions of the test script and this is only reproducible for the async version.
Adding `gc.collect()` at the end makes it all go away, but I feel like this is something that is supposed to be done gradually, not at the end.

default `core.num_threads`
```
Core freed but 3020 filter instance(s) still exist
Core freed but 2414091200 bytes still allocated in framebuffers
```

`core.num_threads = 4`
```
Core freed but 3020 filter instance(s) still exist
Core freed but 914268640 bytes still allocated in framebuffers
```
`core.num_threads = 2`
```
Core freed but 3020 filter instance(s) still exist
Core freed but 741838688 bytes still allocated in framebuffers
```

I'm running this on Arch Linux, a 5900X with 32 GB ram.
Is there a patch I can try to run the garbage the collection more often?

**Comment by dubhater** [comment] 2021-03-06 16:25
What's the script this time and how are you running it?

**Comment by quietvoid** [comment] 2021-03-06 16:29
@dubhater It's the same async script as @DJATOM posted, with the `gc.collect() removed`
It's just ran by python as others did previously.

```
❯ python async.py
Core freed but 3020 filter instance(s) still exist
Core freed but 2119490240 bytes still allocated in framebuffers
```

**Comment by dubhater** [comment] 2021-03-06 18:21
Ah, I thought you ran it with vspipe.

**Comment by quietvoid** [comment] 2021-03-06 18:34
Well the behavior is similar to vspipe, the memory usage increases with the frames processed until it OOMs or completes, whichever comes first.
So I thought this issue is the same, but maybe I'm dealing with something else here.

**Closed** 2021-10-06 06:51 UTC

**Comment by damian101** [comment] 2022-05-06 18:58
Still happens, using vapoursynth-git install script from AUR...
Makes no difference whether I put core.max_cache_size there or not, it's a simple 1080p SSIM downscaling + tonemapping script, uses 5GB of RAM, with 8 workers that's too much for my system's 64 GB RAM.

**Comment by damian101** [comment] 2022-05-08 20:10
I still get this issue, with some vapoursynth scripts I get between 5 and 8 GB vspipe RAM consumption on 240 frame chunks, 1080p output. `core.max_cache_size` is just ignored.
