### ISSUE TITLE
Resize functions not allowing RGB -> YUV conversions

### ISSUE THREAD

**Issue by muxketeer** [vapoursynth/vapoursynth#255] opened 2016-11-18 08:46 UTC
When a script includes RGB input, vspipe is throwing a message that says: 'Resize error 1026: RGB color family cannot be YUV.'

This happens anytime the script has a RGB source and the resize functions are passed a an RGB image. 
even if generating a blank clip that is RGB, this error is thrown.

```import vapoursynth as vs
c = vs.get_core()
ret = c.imwrif.Read(filename="D:\path\to\tiff\mytiffsequence.00%5d.tiff",firstnum=100)
ret = c.resize.Lanczos(clip=ret,width=1920, height=1080,dither_type="error_diffusion", format=vs.YUV420P10, matrix_in_s="2020ncl", transfer_in_s="st2084",primaries_in_s="st432-1",range_in_s="full", matrix_s="2020ncl", transfer_s="st2084", primaries_s="2020",range_s="full")
#ret=c.std.BlankClip(format=vs.RGB24) #also gives the same error
ret.set_output()
```
 
gives the `Resize error 1026: RGB color family cannot be YUV` from vspipe. 
(when running this: 
```
vspipe inputcolorscript.vpy output.yuv
```

However, if the script is nothing more than the tiff sequence, the vspipe command above works.
```
#vspipe works in this script
import vapoursynth as vs
c = vs.get_core()
ret = c.imwrif.Read(filename="D:\path\to\tiff\mytiffsequence.00%5d.tiff",firstnum=100)

ret.set_output() 
```
Is there a more proper, workable, way to convert this RGB image to YUV  (in the manner I'm trying to do in the above resize function)?

**Comment by myrsloik** [comment] 2016-11-18 17:51
This is caused by you not setting matrix (or matrix_s) and therefore the conversion doesn't know which yuv matrix to use. I did however think I caught all the really confusing error messages so I'll look into and try to improve that.

**Comment by muxketeer** [comment] 2016-11-18 18:30
it appears that I did indeed set 'matrix_s.'  You can see in my OP I set `matrix_s="2020ncl"` as an argument to the Resize function. 
Do I need to assign a value to 'matrix_s' in another place too?

**Comment by myrsloik** [comment] 2016-11-18 18:45
I'll investigate it some more then

**Comment by myrsloik** [comment] 2016-11-18 18:57
This happens because you specify a yuv matrix (matrix_in_s="2020ncl") for the input. But the input is rgb so that obviously can't be true and there's only one rgb matrix. Simply drop matrix_in_s and the script works.

**Comment by splinter98** [comment] 2016-11-18 18:57
My guess is you're also specifying matrix_in_s on an RGB image and i think it is complaining about that.

From memory i had similar issues when specifying matrix_s when I was resizing RGB to RGB.

In short only specify a matrix_in(_s) when the input clip is YUV and doesn't have a matrix property assigned to it. And only specify matrix(_s) when converting to YUV. (if using a reference clip however you only need to supply it if you need to override it or that clip doesn't have a matrix property)

**Comment by myrsloik** [comment] 2016-11-18 19:25
Error message has been clarified.

**Closed by myrsloik** 2016-11-18 19:25 UTC

**Comment by muxketeer** [comment] 2016-11-18 23:57
Confirmed. Getting rid of 'matrix_in_s' fixed it.  RGB-> YUV color conversion was proper on output. Thanks, both!

**Comment by HuBandiT** [comment] 2017-12-21 20:02
@myrsloik 

> This happens because you specify a yuv matrix (matrix_in_s="2020ncl") for the input. But the input is rgb so that obviously can't be true and there's only one rgb matrix.

I don't think that is conceptually right though.

There is no such thing as a YUV matrix. It is the original RGB - that was temporarily encoded into YUV (YCbCr) for transport - that has its basic colors defined by the matrix, therefore it is RGB <-> RGB that should be converted using those matrices. And we are already aware of this and do the right thing when converting between YUV <-> RGB - the matrix computations happen in linear RGB, right? (I haven't checked, but am very much hoping.)

So why not make this explicit, tag RGB clips with their color interpretation, and also expose the matrix functionality for RGB <-> RGB as well?

If one wants to process absolute color, there are several possible color spaces. E.g. CIE XYZ, sRGB, Rec.601, Rec.709, Rec.2020, Rec.2100, ACES, etc. then there is also all the vendor-specific (usually wide gamut) spaces/matrices. (These latter are also usually associated with their respective vendor-specific tone mapping aka. "gamma" curves; V-Log, SLog1/2/3, Arri LogC, etc.).

I for one would love to push VS to be able to be a swiss army knife in color, and support a very sophisticated color science (including industry standard absolute color, e.g. ACES) and have as many matrices/tone mappings built in as possible and can be sourced reliably; having the possibility of native floating point processing throughout is a tremendous asset (e.g. optically correct - "gamma aware" - resize using linear light), plus we already are quite color science aware. Adding matrix-awareness into conversions from/to/between various RGB matrices and tone mapping (aka. "gamma") curves is what I think is only missing for proper color input/output, and it looks like a piece of cake compared to all what we have.
